stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - data/data_raw.csv
  process:
    cmd: python process_data.py
    deps:
    - process_data.py
    - data/data_raw.csv
    outs:
    - data/data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data/data_processed.csv
    outs:
    - results/by_region.png
    metrics:
    - results/metrics.json:
        cache: false