name: swiss-farmer-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: CML Run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ML workflow (dvc repro automates the process)
          pip install -r requirements.txt
          dvc repro

          # Post reports as comments in GitHub PRs
          git fetch --prune
          dvc metrics diff --show-md main > report.md

          # Add figures to the report
          echo "## Validating results by region"
          cml-publish results/by_region.png --md >> report.md
          cml-send-comment report.md
